import type { Metadata } from "next";
import "@repo/ui/globals.css";
import { Toaster } from "@repo/ui/components/ui/toaster";
import AppProviders from "./AppProviders";
import { Roboto } from "next/font/google";
import NavBar from "../layouts/navigation/NavBar";
import Footer from "../layouts/footer/Footer";
import ChatWidget from "../features/chatbot/components/ChatWidget";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${roboto.className} antialiased min-h-screen flex flex-col`}
      >
        <AppProviders>
          <NavBar />
          <main className="flex-1">{children}</main>
          <Footer />
          <ChatWidget />
        </AppProviders>
        <Toaster />
      </body>
    </html>
  );
}
